import type { ModelInfo } from './types';

export const CHAT_MODEL_REGISTRY: ModelInfo[] = [
  {
    id: 'gpt-6-astra',
    name: 'GPT 6 Astra',
    platform: 'openai',
    input_price: 10,
    output_price: 50,
    context_window: 1050000,
    max_output_tokens: 128000,
    capabilities: ['chat', 'reasoning'],
  },
  {
    id: 'gpt-5.6-sol',
    name: 'GPT 5.6 Sol',
    platform: 'openai',
    input_price: 5,
    output_price: 30,
    context_window: 1050000,
    max_output_tokens: 128000,
    capabilities: ['chat', 'reasoning'],
  },
  {
    id: 'gpt-5.6-terra',
    name: 'GPT 5.6 Terra',
    platform: 'openai',
    input_price: 2.5,
    output_price: 15,
    context_window: 1050000,
    max_output_tokens: 128000,
    capabilities: ['chat', 'reasoning'],
  },
  {
    id: 'gpt-5.6-luna',
    name: 'GPT 5.6 Luna',
    platform: 'openai',
    input_price: 1,
    output_price: 6,
    context_window: 1050000,
    max_output_tokens: 128000,
    capabilities: ['chat', 'reasoning'],
  },
  {
    id: 'gpt-5.5',
    name: 'GPT 5.5',
    platform: 'openai',
    input_price: 5,
    output_price: 30,
    context_window: 400000,
    max_output_tokens: 128000,
    capabilities: ['chat', 'reasoning'],
  },
  {
    id: 'gpt-5.3-codex-spark',
    name: 'GPT 5.3 Codex Spark',
    platform: 'openai',
    input_price: 1.75,
    output_price: 14,
    context_window: 128000,
    max_output_tokens: 128000,
    capabilities: ['chat', 'reasoning'],
  },
];
